package Project;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Scanner;



//==============================InterFace============================================
interface Intrest {

	public double calculateIntrest();

}

//=========================================Model=====================================

//=================================================Account=================================

abstract class Account {

	static int counter = 1;

	int accno;
	String acHolderName;
	double balance;
	LocalDate lastTransactionDate;
	int transactionCount;
	Transaction[] transactions;

	// Default Constructor
	public Account() {
		super();
		this.accno = generateUniqueAccountNumber();
		this.acHolderName = "Shubham Akymwar";
		this.balance = 545;
		this.lastTransactionDate = LocalDate.now();
		this.transactionCount = 1;

	}

	// account number autoGenerated function
	public static int generateUniqueAccountNumber() {
		int year = LocalDate.now().getYear(); // Example: 2025
		int rand = (int) (Math.random() * 900) + 100; // 100–999 random 3 digits

		return year * 100000 + rand * 100 + (counter++ % 100);
	}

	// Parameterized Constructor

	public Account(String acHolderName, double balance) {
		super();
		this.accno = generateUniqueAccountNumber();
		this.acHolderName = acHolderName;
		this.balance = balance;
		this.lastTransactionDate = LocalDate.now();

	}

	public int getAccno() {
		return accno;
	}

	public void setAccno(int accno) {
		this.accno = accno;
	}

	public String getAcHolderName() {
		return acHolderName;
	}

	public void setAcHolderName(String acHolderName) {
		this.acHolderName = acHolderName;
	}

	public double getBalance() {
		return balance;
	}

	public void setBalance(double balance) {
		this.balance = balance;
	}

	public LocalDate getLastTransactionDate() {
		return lastTransactionDate;
	}

	public void setLastTransactionDate(LocalDate lastTransactionDate) {
		this.lastTransactionDate = lastTransactionDate;
	}

	public int getTransactionCount() {
		return transactionCount;
	}

	public void setTransactionCount(int transactionCount) {
		this.transactionCount = transactionCount;
	}

	public Transaction[] getTransactions() {
		return transactions;
	}

	public void setTransactions(Transaction[] transactions) {
		this.transactions = transactions;
	}

	// Deposit Method
	public void deposit(double amount) {

		if (amount <= 0) {
			System.out.println("Deposit Failed: Amount must be greater than zero.");
			return;
		}

		// Balance update
        this.balance += amount;

		// Add transaction
		addTransaction(amount, "DEPOSIT");

		System.out.println("Deposit Successful: ₹" + amount);
		System.out.println("Updated Balance: ₹" + this.balance);
	}

	public void addTransaction(double amount, String type) {

		// transaction object created
		Transaction t = new Transaction(this.accno, amount, type);

		// 2. If array is null initialize it
		if (transactions == null) {
			transactions = new Transaction[100];
		}

		// 3. Add transaction to array
		transactions[transactionCount] = t;
		transactionCount++;

		// 4. Update balance
		if (type.equalsIgnoreCase("DEPOSIT")) {
			//this.balance += amount;
		} else if (type.equalsIgnoreCase("WITHDRAW")) {
			//
			this.balance -= amount;
		}

		// 5. Update last transaction date
		this.lastTransactionDate = LocalDate.now();
	}

	// addTransaction ends here

	public abstract void withdraw(double amonut);

	// display function

	public void display() {
		System.out.println("----- Account Details -----");
		System.out.println("Account Number        : " + this.accno);
		System.out.println("Account Holder Name   : " + this.acHolderName);
		System.out.println("Balance               : " + this.balance);
		System.out.println("Last Transaction Date : " + this.lastTransactionDate);
		System.out.println("Transaction Count     : " + this.transactionCount);

	}

}// class Account ends here

//------------------------------------------------CurrentAccount-------------------------------------

class CurrentAccount extends Account {
	double overDraftlimit;

	// Default Constructor
	public CurrentAccount() {
		super();
		this.overDraftlimit = 5000;

	}

	// Parameterized Constructor
	public CurrentAccount(String acHolderName, double balance, double overDraftlimit) {
		super(acHolderName, balance);
		this.overDraftlimit = overDraftlimit;

	}

	// setters and getters
	public double getOverDraftlimit() {
		return overDraftlimit;
	}

	public void setOverDraftlimit(double overDraftlimit) {
		this.overDraftlimit = overDraftlimit;
	}

	// withdraw function
	public void withdraw(double amount) {

		if (amount < 0) {

			System.out.println("Invalid Amount.....");
			return;
		}

		double availableBal = balance + overDraftlimit;

		if (amount > availableBal) {
			System.out.println("Overdraft limit exceeded!");
			return;
		}

		// deduct amount
		this.balance -= amount;

		// update Last transaction Date
		this.lastTransactionDate = LocalDate.now();

		// add transaction
		addTransaction(amount, "WITHDRAW");

		System.out.println("₹" + amount + " withdrawn successfully.");

	}// withdraw ends here

	public void display() {
		super.display();
		System.out.println("OverDraft Limit : " + this.overDraftlimit);
		System.out.println("Account type : Current Account");

	}

}// Current account ends here

//-------------------------------------------------------------Loan Account--------------------------------------------

class LoanAccount extends Account implements Intrest {
	int credirScore;
	double emi;
	double loanAmount;
	double intrestRate;

	public LoanAccount() {
		super();
		this.credirScore = 560;
		this.emi = 4500;
		this.loanAmount = 50000;
		this.intrestRate = 5.8;

	}

	// Parameterized Constructor
	public LoanAccount(String acHolderName, double balance, int credirScore, double emi, double loanAmount,
			double intrestRate) {
		super(acHolderName, balance);
		this.credirScore = credirScore;
		this.emi = emi;
		this.loanAmount = loanAmount;
		this.intrestRate = intrestRate;
	}

	public int getCredirScore() {
		return credirScore;
	}

	public void setCredirScore(int credirScore) {
		this.credirScore = credirScore;
	}

	public double getEmi() {
		return emi;
	}

	public void setEmi(double emi) {
		this.emi = emi;
	}

	public double getLoanAmount() {
		return loanAmount;
	}

	public void setLoanAmount(double loanAmount) {
		this.loanAmount = loanAmount;
	}

	public double getIntrestRate() {
		return intrestRate;
	}

	public void setIntrestRate(double intrestRate) {
		this.intrestRate = intrestRate;
	}

	// withdraw Method
	public void withdraw(double Amount) {
		System.out.println("Withdraw method cant be awailable......");
	}

	public double calculateIntrest() {

		// Monthly reducing balance interest
		double monthlyInterest = (loanAmount * (intrestRate / 100)) / 12;

		return monthlyInterest;
	}

	public void PayEmi(double amount) {

		if (amount < 0) {
			System.out.println("Invalid Amount.....");
			return;
		}

		// monthly interest
		double monthlyInterest = (loanAmount * (intrestRate / 100)) / 12;

		if (amount < monthlyInterest) {
			System.out.println("EMI is too low. It cannot even cover monthly interest.");
			return;
		}

		// 3. Calculate principal part
		double principalPaid = amount - monthlyInterest;

		// update LoanAmount

		loanAmount -= principalPaid;

		// Add transaction
		addTransaction(amount, "Emi Installment Paid");

		// update Last Transaction date
		this.lastTransactionDate = LocalDate.now();

		System.out.println("EMI Payment Successful.");

	}// PayEmi method ends here

	public void settleFullLoan(double amount) {
		if (loanAmount <= 0) {
			System.out.println("Loan is already settled.");
			return;

		}

		// Calculate last month's interest
		double monthlyInterest = (loanAmount * (intrestRate / 100)) / 12;

		// Total amount required to close the loan
		double totalPayable = loanAmount + monthlyInterest;

		// settle loan amount
		loanAmount = 0;

		// Update last payment date
		lastTransactionDate = LocalDate.now();

		// add transaction
		addTransaction(amount, "Deposit");

		System.out.println("Loan successfully settled. Total Paid: " + totalPayable);
	}

	public void display() {
		super.display();
		System.out.println("Loan Amount       : " + loanAmount);
		System.out.println("Interest Rate     : " + intrestRate);
		System.out.println("Credit Score      : " + credirScore);
		System.out.println("Monthly EMI       : " + emi);
		System.out.println("Outstanding Amount: " + loanAmount);
		System.out.println("Last Payment Date : " + lastTransactionDate);
		System.out.println("Account type : Loan Account");
		System.out.println("--------------------------------");
	}

}
// Loan Account ends here

// -----------------------------------------------Salary
// Account---------------------------------------------
class SalaryAccount extends Account {
	String employerName;
	LocalDate lastTransactionDate;
	boolean isFrozen;

	// Default Parameter
	public SalaryAccount() {
		super();
		this.employerName = "Fistbit solution";

	}

	// Parameterized constructor

	public SalaryAccount(String acHolderName, double balance, String employerName) {
		super(acHolderName, balance);
		this.employerName = employerName;

	}

	// setters and getters
	public String getEmployerName() {
		return employerName;
	}

	public void setEmployerName(String employerName) {
		this.employerName = employerName;
	}

	public LocalDate getLastTransactionDate() {
		return lastTransactionDate;
	}

	public void setLastTransactionDate(LocalDate lastTransactionDate) {
		this.lastTransactionDate = lastTransactionDate;
	}

	public boolean isFrozen() {
		return isFrozen;
	}

	public void setFrozen(boolean isFrozen) {
		this.isFrozen = isFrozen;
	}

	// withdraw Function
	public void withdraw(double amount) {

		if (isFrozen) {
			System.out.println("Withdrawal Failed! Account is frozen due to inactivity.");
			return;
		}

		// 2. Check last transaction date (2 months rule)
		LocalDate today = LocalDate.now();
		LocalDate limitDate = lastTransactionDate.plusMonths(2);

		if (today.isAfter(limitDate)) {
			isFrozen = true;
			System.out.println("Account Frozen! No transactions in the last 2 months.");
			return;
		}

		if (amount <= 0) {
			System.out.println("Invalid withdrawal amount!");
			return;
		}
		// deduct amount
		this.balance -= amount;

		// Add withdrawal transaction
		addTransaction(amount, "WITHDRAW");

		this.lastTransactionDate = LocalDate.now();

		System.out.println("₹" + amount + " withdrawn successfully.");

	}// withdraw ends here

	public void display() {
		super.display();
		System.out.println("Employer Name         : " + this.employerName);
		System.out.println("Last Transaction Date : " + this.lastTransactionDate);
		System.out.println("Account Frozen Status : " + (this.isFrozen ? "Frozen" : "Active"));
		System.out.println("Account type : Salary Account");
		System.out.println("----------------------------------");
	}

}// class salary account ends here

//-----------------------------------------------------------------Saving Account-------------------------------------------------------------

class SavingAccount extends Account implements Intrest {

	double minBalance;
	double intrestRate;

	// Default constructor
	public SavingAccount() {
		super();
		this.minBalance = 5000;
		this.intrestRate = 5.8;

	}

	// Parameterized constructor
	public SavingAccount(String acHolderName, double balance, double minBalance, double intrestRate) {
		super(acHolderName, balance);
		this.minBalance = minBalance;
		this.intrestRate = intrestRate;
	}

	// setters getters
	public double getMinBalance() {
		return minBalance;
	}

	public void setMinBalance(double minBalance) {
		this.minBalance = minBalance;
	}

	public double getIntrestRate() {
		return intrestRate;
	}

	public void setIntrestRate(double intrestRate) {
		this.intrestRate = intrestRate;
	}

	// withdraw method of saving account

	public void withdraw(double amount) {

		if (amount <= 0) {
			System.out.println("Invalid amount......");
			return;
		}

		if (balance - amount < minBalance) {
			System.out.println("Withdrawal failed! Minimum balance of ₹" + minBalance + " must be maintained.");
			return;

		}

		// Deduct balance
		this.balance -= amount;

		// Add transaction entry
		addTransaction(amount, "WITHDRAW");

		// Update last transaction date
		this.lastTransactionDate = LocalDate.now();

		System.out.println("₹" + amount + " withdrawn successfully.");

	}// withdraw ends here

	// CalculateIntrest
	public double calculateIntrest() {

		return this.balance * (intrestRate / 100);
	}
	// CalculateIntrest ends here

	public void display() {
		super.display();
		System.out.println("Minimum Balance       : " + this.minBalance);
		System.out.println("Interest Rate         : " + this.intrestRate);
		System.out.println("Account type : Saving Account");
	}

}// Class SavingAccount ends here

// ==================================================Transaction====================================================================

class Transaction {
	static int counter = 10000;
	String transactionId;
	int accountNumber;
	double amount;
	String type;
	LocalDateTime date;

	// Default Constructor
	public Transaction() {
		super();
		this.transactionId = "TXN-" + System.currentTimeMillis() + "-" + (++counter);
		this.accountNumber = 1458575;
		this.amount = 4522;
		this.type = "Deposit";
		this.date = LocalDateTime.now();

	}

	// Parameterized Constructor
	public Transaction(int accountNumber, double amount, String type) {
		super();
		this.transactionId = "TXN-" + System.currentTimeMillis() + "-" + (++counter);
		this.accountNumber = accountNumber;
		this.amount = amount;
		this.type = type;
		this.date = LocalDateTime.now();
	}

	// setters and getters
	public String getTransactionId() {
		return transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	public int getAccountNumber() {
		return accountNumber;
	}

	public void setAccountNumber(int accountNumber) {
		this.accountNumber = accountNumber;
	}

	public double getAmount() {
		return amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	// display Function

	public void display() {
		System.out.println("Transaction ID : " + this.transactionId);
		System.out.println("Account Number : " + this.accountNumber);
		System.out.println("Amount : " + this.amount);
		System.out.println("Transaction Type : " + this.type);
		System.out.println("Transaction Date : " + this.date);
	}

}
//=========================transaction ends ================================================================

// ===============================================================BankModel====================================================

class BankModel {
	Account[] accounts;
	int accountCount;

	// Default parameter

	public BankModel() {
		super();
		accounts = new Account[100];
		this.accountCount = 0;
	}

	// setters and getters

	public int getAccountCount() {
		return accountCount;
	}

	// Add Account in the array
	public void addAccount(Account acc) {

		if (accountCount < accounts.length) {
			accounts[accountCount++] = acc;
		} else {
			System.out.println("Account storage full!");
		}

	}// end add account

	public Account getAccount(int acNumber) {

		for (int i = 0; i < accountCount; i++) {

			if (accounts[i].getAccno() == acNumber) {
				return accounts[i];
			}
		}
		return null;
	}// GetAccount ends here

	// getAllAccounts method

	public Account[] getAllAccounts() {
		return accounts;
	}

}
//===========================bank model ends here=========================================


//================================Bank Controller==================================


 class BankController {

     BankModel model;
     BankView view;
     Scanner sc;

    public BankController() {
        model = new BankModel();
        view = new BankView();
        sc = new Scanner(System.in);
    }

    // START APP
    public void startApp() {
        int choice;

        while (true) {
            view.showMainMenu();
            choice = sc.nextInt();
            sc.nextLine();
            handleUserChoice(choice);
        }
    }

    // HANDLE MENU CHOICES
    public void handleUserChoice(int choice) {
        switch (choice) {

            case 1: createAccount(); break;
            case 2: deposit(); break;
            case 3: withdraw(); break;
            case 4: transfer(); break;
            case 5: applyLoan(); break;
            case 6: payEMI(); break;
            case 7: settleLoan(); break;
            case 8: showAccountDetails(); break;
            case 9: showAllAccounts(); break;
            case 10: showMiniStatement(); break;
            case 11: generateEODReport(); break;

            case 0:
                System.out.println("Exiting Application...");
                System.exit(0);
                break;

            default:
                view.showMessage("Invalid Choice!");
        }
    }

    // CREATE ACCOUNT
    public void createAccount() {

        view.showMessage("Enter Holder Name:");
        String name = sc.nextLine();

        view.showMessage("Enter Opening Balance:");
        double bal = sc.nextDouble();

        view.showMessage("Choose Account Type:");
        view.showMessage("1. Saving Account");
        view.showMessage("2. Salary Account");
        view.showMessage("3. Current Account");

        int type = sc.nextInt();
        Account acc;

        if (type == 1) acc = new SavingAccount(name, bal, 1000, 5.8);
        else if (type == 2) acc = new SalaryAccount(name, bal, "Company");
        else if (type == 3) acc = new CurrentAccount(name, bal, 5000);
        else {
            view.showMessage("Invalid Account Type!");
            return;
        }

        model.addAccount(acc);
        view.showMessage("Account Created Successfully!");
       
    }

    // DEPOSIT
    public void deposit() {
        int accNo = view.getAccountInput();
        double amt = view.getDepositInput();

        Account acc = model.getAccount(accNo);
        if (acc == null) {
            view.showMessage("Account Not Found!");
            return;
        }

        acc.deposit(amt);
    }

    // WITHDRAW
    public void withdraw() {
        int accNo = view.getAccountInput();
        double amt = view.getWithdrawInput();

        Account acc = model.getAccount(accNo);

        if (acc == null) {
            view.showMessage("Account Not Found!");
            return;
        }

        acc.withdraw(amt);
    }

    // TRANSFER
    public void transfer() {
        view.showMessage("Enter Sender Account:");
        int fromAccNo = sc.nextInt();

        view.showMessage("Enter Receiver Account:");
        int toAccNo = sc.nextInt();

        view.showMessage("Enter Amount:");
        double amt = sc.nextDouble();

        Account from = model.getAccount(fromAccNo);
        Account to = model.getAccount(toAccNo);

        if (from == null || to == null) {
            view.showMessage("Invalid Account Numbers!");
            return;
        }

        from.withdraw(amt);
        to.deposit(amt);

        view.showMessage("Transfer Successful!");
    }

    // APPLY LOAN (Simple Version)
    public void applyLoan() {

        view.showMessage("Loan Holder Name:");
        String name = sc.nextLine();

        view.showMessage("Enter Loan Amount:");
        double loanAmount = sc.nextDouble();

        view.showMessage("Enter Interest Rate:");
        double interest = sc.nextDouble();

        view.showMessage("Enter Credit Score:");
        int creditScore = sc.nextInt();

        view.showMessage("Enter EMI Amount:");
        double emi = sc.nextDouble();

        LoanAccount loan = new LoanAccount(
                name,
                0,            // opening balance
                creditScore,
                emi,
                loanAmount,
                interest
        );

        model.addAccount(loan);
        view.showMessage("Loan Account Created Successfully!");
    }

    // PAY EMI
    public void payEMI() {
        int accNo = view.getAccountInput();
        Account acc = model.getAccount(accNo);

        if (!(acc instanceof LoanAccount)) {
            view.showMessage("Not a Loan Account!");
            return;
        }

        view.showMessage("Enter EMI Amount:");
        double amt = sc.nextDouble();

        ((LoanAccount) acc).PayEmi(amt);
    }

    // SETTLE LOAN
    public void settleLoan() {
        int accNo = view.getAccountInput();
        Account acc = model.getAccount(accNo);

        if (!(acc instanceof LoanAccount)) {
            view.showMessage("Not a Loan Account!");
            return;
        }

        view.showMessage("Enter Payment Amount:");
        double amt = sc.nextDouble();

        ((LoanAccount) acc).settleFullLoan(amt);
    }

    // SHOW ACCOUNT DETAILS
    public void showAccountDetails() {
        int accNo = view.getAccountInput();
        Account acc = model.getAccount(accNo);

        view.showAccount(acc);
    }

    // SHOW ALL ACCOUNTS
    public void showAllAccounts() {
        view.showAllAccounts(model.getAllAccounts());
    }
    //GenerateReprtEnd of the day
    
    public void generateEODReport() {
        Account[] accounts = model.getAllAccounts();
        if (accounts == null || accounts.length == 0) {
            view.showMessage("No accounts available for EOD report.");
            return;
        }

        double totalDeposits = 0;
        double totalWithdrawals = 0;
        double totalEMI = 0;

        for (int i = 0; i < accounts.length; i++) {
            Account acc = accounts[i];
            if (acc == null) continue;

            Transaction[] txns = acc.getTransactions();
            int txnCount = acc.getTransactionCount();

            if (txns != null) {
                for (int j = 1; j < txnCount; j++) { // skip index 0 (opening balance)
                    if (txns[j] == null) continue;

                    // only count today's transactions
                    if (txns[j].date.toLocalDate().equals(LocalDate.now())) {
                        String type = txns[j].type.toUpperCase();
                        if (type.equals("DEPOSIT")) totalDeposits += txns[j].amount;
                        else if (type.equals("WITHDRAW")) totalWithdrawals += txns[j].amount;
                        else if (type.contains("EMI")) totalEMI += txns[j].amount;
                    }
                }
            }
        }

        view.showEODReport(accounts.length, totalDeposits, totalWithdrawals, totalEMI);
    }

    // MINI STATEMENT
    public void showMiniStatement() {
        int accNo = view.getAccountInput();
        Account acc = model.getAccount(accNo);

        view.showMiniStatement(acc);
    }
    
}

 
 //===============================Controllers ends here===================================
 
 
 //====================================Bank view ============================================
 ;

  class BankView {
      Scanner sc;

     public BankView() {
         sc = new Scanner(System.in);
     }

     public void showMainMenu() {
         System.out.println("\n===== MAIN MENU =====");
         System.out.println("1. Create Account");
         System.out.println("2. Deposit");
         System.out.println("3. Withdraw");
         System.out.println("4. Transfer");
         System.out.println("5. Apply Loan");
         System.out.println("6. Pay EMI");
         System.out.println("7. Settle Loan");
         System.out.println("8. Show Account Details");
         System.out.println("9. Show All Accounts");
         System.out.println("10. Mini Statement");
         System.out.println("11. End of Day Report");
         System.out.println("0. Exit");
         System.out.print("Enter choice: ");
     }

     public int getAccountInput() {
         System.out.print("Enter account number: ");
         return sc.nextInt();
     }

     public double getDepositInput() {
         System.out.print("Enter amount to deposit: ");
         return sc.nextDouble();
     }

     public double getWithdrawInput() {
         System.out.print("Enter amount to withdraw: ");
         return sc.nextDouble();
     }

     public double[] getLoanInput() {
         double[] data = new double[4];
         System.out.print("Enter loan amount: ");
         data[0] = sc.nextDouble();
         System.out.print("Enter interest rate: ");
         data[1] = sc.nextDouble();
         System.out.print("Enter credit score: ");
         data[2] = sc.nextDouble();
         System.out.print("Enter EMI amount: ");
         data[3] = sc.nextDouble();
         return data;
     }

     public void showMessage(String msg) {
         System.out.println(msg);
     }

     public void showAccount(Account acc) {
         if (acc == null) {
             System.out.println("Account not found!");
             return;
         }
         acc.display();
     }

     // ---- Modified to use only arrays ----
     public void showAllAccounts(Account[] accounts) {
         if (accounts == null || accounts.length == 0) {
             System.out.println("No accounts available.");
             return;
         }

         System.out.println("----- ALL ACCOUNTS -----");
         for (int i = 0; i < accounts.length; i++) {
             if (accounts[i] != null) {
                 accounts[i].display();
                 System.out.println("------------------------");
             }
         }
     }
     //Show End Of day Report------------------------
     public void showEODReport(int totalAccounts, double totalDeposits, double totalWithdrawals, double totalEMI) {
    	    System.out.println("\n===== END OF DAY REPORT =====");
    	    System.out.println("Total Accounts         : " + totalAccounts);
    	    System.out.println("Total Deposits Today   : ₹" + totalDeposits);
    	    System.out.println("Total Withdrawals Today: ₹" + totalWithdrawals);
    	    System.out.println("Total EMI Paid Today   : ₹" + totalEMI);
    	    System.out.println("==============================\n");
    	}


     public void showMiniStatement(Account acc) {
         if (acc == null) {
             System.out.println("Account not found!");
             return;
         }

         Transaction[] txns = acc.getTransactions();
         int txnCount = acc.getTransactionCount();

         if (txns == null || txnCount <= 1) {
             System.out.println("No transactions available.");
             return;
         }

         System.out.println("----- Mini Statement for Account " + acc.getAccno() + " -----");
         for (int i = 1; i < txnCount; i++) { // start from 1 if 0 is opening balance
             if (txns[i] != null) {
                 txns[i].display();
                 System.out.println("--------------------------------");
             }
         }
     }
 }
//===================================================bankView Ends here========================================
  
  
//==========================================BankApp============================================================
  public class BankApp {
	    public static void main(String[] args) {
	        BankController controller = new BankController();
	        controller.startApp();
	    }
	}
